//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataTools.DtoGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODataTools.DtoGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DataSvcUtilGUIGenerateBindableObjects ähnelt.
        /// </summary>
        internal static string DataSvcUtilGUIGenerateBindableObjects {
            get {
                return ResourceManager.GetString("DataSvcUtilGUIGenerateBindableObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DataSvcUtilGUILanguage ähnelt.
        /// </summary>
        internal static string DataSvcUtilGUILanguage {
            get {
                return ResourceManager.GetString("DataSvcUtilGUILanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DataSvcUtilGUIOutputFile ähnelt.
        /// </summary>
        internal static string DataSvcUtilGUIOutputFile {
            get {
                return ResourceManager.GetString("DataSvcUtilGUIOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DataSvcUtilGUIsInstalled ähnelt.
        /// </summary>
        internal static string DataSvcUtilGUIsInstalled {
            get {
                return ResourceManager.GetString("DataSvcUtilGUIsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DataSvcUtilGUITitle ähnelt.
        /// </summary>
        internal static string DataSvcUtilGUITitle {
            get {
                return ResourceManager.GetString("DataSvcUtilGUITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DataSvcUtilGUIVersion ähnelt.
        /// </summary>
        internal static string DataSvcUtilGUIVersion {
            get {
                return ResourceManager.GetString("DataSvcUtilGUIVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorDataClassOptions ähnelt.
        /// </summary>
        internal static string DtoGeneratorDataClassOptions {
            get {
                return ResourceManager.GetString("DtoGeneratorDataClassOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorDataSvcUtilGuiDescription ähnelt.
        /// </summary>
        internal static string DtoGeneratorDataSvcUtilGuiDescription {
            get {
                return ResourceManager.GetString("DtoGeneratorDataSvcUtilGuiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorDataSvcUtilGuiTitle ähnelt.
        /// </summary>
        internal static string DtoGeneratorDataSvcUtilGuiTitle {
            get {
                return ResourceManager.GetString("DtoGeneratorDataSvcUtilGuiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorDescription ähnelt.
        /// </summary>
        internal static string DtoGeneratorDescription {
            get {
                return ResourceManager.GetString("DtoGeneratorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorEdmxFile ähnelt.
        /// </summary>
        internal static string DtoGeneratorEdmxFile {
            get {
                return ResourceManager.GetString("DtoGeneratorEdmxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorEdmxSuccessfullyLoaded ähnelt.
        /// </summary>
        internal static string DtoGeneratorEdmxSuccessfullyLoaded {
            get {
                return ResourceManager.GetString("DtoGeneratorEdmxSuccessfullyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorFailedToLoadEdmxFile ähnelt.
        /// </summary>
        internal static string DtoGeneratorFailedToLoadEdmxFile {
            get {
                return ResourceManager.GetString("DtoGeneratorFailedToLoadEdmxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorGeneratedSourceFile ähnelt.
        /// </summary>
        internal static string DtoGeneratorGeneratedSourceFile {
            get {
                return ResourceManager.GetString("DtoGeneratorGeneratedSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorGenerateSingleFilePerDto ähnelt.
        /// </summary>
        internal static string DtoGeneratorGenerateSingleFilePerDto {
            get {
                return ResourceManager.GetString("DtoGeneratorGenerateSingleFilePerDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorGenerateWithAttributes ähnelt.
        /// </summary>
        internal static string DtoGeneratorGenerateWithAttributes {
            get {
                return ResourceManager.GetString("DtoGeneratorGenerateWithAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorGeneratorFinished ähnelt.
        /// </summary>
        internal static string DtoGeneratorGeneratorFinished {
            get {
                return ResourceManager.GetString("DtoGeneratorGeneratorFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorLog ähnelt.
        /// </summary>
        internal static string DtoGeneratorLog {
            get {
                return ResourceManager.GetString("DtoGeneratorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorModelFiles ähnelt.
        /// </summary>
        internal static string DtoGeneratorModelFiles {
            get {
                return ResourceManager.GetString("DtoGeneratorModelFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorModelSourceFile ähnelt.
        /// </summary>
        internal static string DtoGeneratorModelSourceFile {
            get {
                return ResourceManager.GetString("DtoGeneratorModelSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorModelSourceUrl ähnelt.
        /// </summary>
        internal static string DtoGeneratorModelSourceUrl {
            get {
                return ResourceManager.GetString("DtoGeneratorModelSourceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorOutputDirectory ähnelt.
        /// </summary>
        internal static string DtoGeneratorOutputDirectory {
            get {
                return ResourceManager.GetString("DtoGeneratorOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorSelectModelFile ähnelt.
        /// </summary>
        internal static string DtoGeneratorSelectModelFile {
            get {
                return ResourceManager.GetString("DtoGeneratorSelectModelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorTargetNamespace ähnelt.
        /// </summary>
        internal static string DtoGeneratorTargetNamespace {
            get {
                return ResourceManager.GetString("DtoGeneratorTargetNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorTiles ähnelt.
        /// </summary>
        internal static string DtoGeneratorTiles {
            get {
                return ResourceManager.GetString("DtoGeneratorTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorTitle ähnelt.
        /// </summary>
        internal static string DtoGeneratorTitle {
            get {
                return ResourceManager.GetString("DtoGeneratorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DtoGeneratorViewTitle ähnelt.
        /// </summary>
        internal static string DtoGeneratorViewTitle {
            get {
                return ResourceManager.GetString("DtoGeneratorViewTitle", resourceCulture);
            }
        }
    }
}
